### PR TITLE
TPC support

### LINKED ISSUE #177: TPC inheritance fails with an abstract parent
I've got an exception after using inheritance:

```C#
using Microsoft.EntityFrameworkCore;

namespace EfCoreTpc;
public class Program
{
    public static async Task Main(params string[] args)
    {
        IHost host = Host.CreateDefaultBuilder()
        .ConfigureServices(services =>
        {
            services.AddDbContext<MyContext>(builder =>
            {
                builder.UseNpgsql("Host=localhost;Port=7435;Database=testdb;Username=admin;Password=testpass")
                .UseSnakeCaseNamingConvention();
            });
        })
        .Build();

        await host.RunAsync();
    }
}

public abstract class Parent
{
    public int Id { get; set; }
}

public class Child : Parent
{
}

public class MyContext : DbContext
{
    public DbSet<Child> Childs{ get; set; }

    public MyContext(DbContextOptions options)
        : base(options)
    {

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Parent>(builder =>
        {
            builder.UseTpcMappingStrategy();
        });
    }
}
```

The exception exists just in TPC inheritance. Exception message:

> The corresponding CLR type for entity type 'Parent' cannot be instantiated, but the entity type was mapped to 'parent' using the 'TPC' mapping strategy. Only instantiable types should be mapped. See https://go.microsoft.com/fwlink/?linkid=2130430 for more information.

### LINKED ISSUE #181: Basic TPC support

### PR DESCRIPTION
**Pull request by roji**
Also turn on nullability for the tests

Closes #181
Closes #177

### CODE REVIEW

File: EFCore.NamingConventions/Internal/NameRewritingConvention.cs [hunk 1]
```diff
@@ -34,7 +34,7 @@ public NameRewritingConvention(INameRewriter nameRewriter)
 
         // Note that the base type is null when the entity type is first added - a base type only gets added later
         // (see ProcessEntityTypeBaseTypeChanged). But we still have this check for safety.
-        if (entityType.BaseType is null)
+        if (entityType.BaseType is null && !entityType.ClrType.IsAbstract)
```
Comment (at-besa) [inline EFCore.NamingConventions/Internal/NameRewritingConvention.cs:37]: this obviously breaks that all abstract tables are not rewritten and would stay in a different case, when UseSnakeCaseNamingConvention is applied the tablename would stay in normal case, which would break a lot of existing code and tables.
related to #184

File: EFCore.NamingConventions/Internal/NameRewritingConvention.cs [hunk 2]
```diff
@@ -57,10 +57,10 @@ public NameRewritingConvention(INameRewriter nameRewriter)
     {
         var entityType = entityTypeBuilder.Metadata;
 
-        if (newBaseType is null)
+        if (newBaseType is null || entityType.GetMappingStrategy() == RelationalAnnotationNames.TpcMappingStrategy)
         {
             // The entity is getting removed from a hierarchy. Set the (rewritten) TableName.
-            if (entityType.GetTableName() is { } tableName)
+            if (entityType.GetTableName() is { } tableName && !entityType.ClrType.IsAbstract)
```
Comment (at-besa) [inline EFCore.NamingConventions/Internal/NameRewritingConvention.cs:63]: this obviously breaks that all abstract tables are not rewritten and would stay in a different case, when UseSnakeCaseNamingConvention is applied the tablename would stay in normal case, which would break a lot of existing code and tables.
related to #184

**Review by at-besa — COMMENTED** [review]
related to #184
